export const produits = [
  {
    nom: "Poulet frit",
    details: "Ailes de poulet frites avec une sauce piquante",
    prix: 8.99,
    top: true,
    categorie: "monde",
    ingredients: ["poulet", "farine", "huile", "sauce piquante"],
  },
  {
    nom: "Pad Thai",
    details: "Nouilles de riz sautées avec des crevettes, des cacahuètes et des légumes",
    prix: 11.99,
    top: true,
    categorie: "thai",
    ingredients: ["nouilles de riz", "crevettes", "cacahuètes", "légumes"],
  },
  {
    nom: "Riz cantonais",
    details: "Riz frit avec des petits pois, des carottes et des oeufs",
    prix: 6.99,
    top: false,
    categorie: "chinois",
    ingredients: ["riz", "petits pois", "carottes", "oeufs"],
  },
  {
    nom: "Fufu",
    details: "Boulettes de manioc pilées servies avec une soupe",
    prix: 9.99,
    top: true,
    categorie: "congolais",
    ingredients: ["manioc", "eau", "viande", "légumes"],
  },
  {
    nom: "Cocktail de fruits",
    details: "Mélange de fruits frais coupés en dés",
    prix: 4.99,
    top: false,
    categorie: "boisson",
    ingredients: ["ananas", "mangue", "kiwi", "fraise"],
  },
  {
    nom: "Nouilles sautées",
    details: "Nouilles sautées avec des légumes et des crevettes",
    prix: 10.99,
    top: true,
    categorie: "monde",
    ingredients: ["nouilles", "légumes", "crevettes", "sauce soja"],
  },
  {
    nom: "Poulet au curry",
    details: "Poulet cuit avec du curry et des légumes",
    prix: 12.99,
    top: true,
    categorie: "thai",
    ingredients: ["poulet", "curry", "légumes", "lait de coco"],
  },
  {
    nom: "Haricots verts sautés",
    details: "Haricots verts sautés avec de l'ail et du gingembre",
    prix: 5.99,
    top: false,
    categorie: "chinois",
    ingredients: ["haricots verts", "ail", "gingembre", "sauce soja"],
  },
  {
    nom: "Saka-saka",
    details: "Feuilles de manioc pilées avec des légumes",
    prix: 8.99,
    top: true,
    categorie: "congolais",
    ingredients: ["manioc", "légumes", "huile de palme"],
  },
  {
    nom: "Kissoulou",
    details: "Feuilles avec arachides et sauce piquante",
    prix: 10.99,
    top: true,
    categorie: "congolais",
    ingredients: ["manioc", "légumes", "huile de palme"],
  },
  {
    nom: "Cocktail de fruits pimentés",
    details: "Mélange de fruits frais coupés en dés et du ments",
    prix: 7.99,
    top: false,
    categorie: "boisson",
    ingredients: ["ananas", "mangue", "kiwi", "fraise"],
  },
  {
    nom: "couscous",
    details: "couscous de blé avec des petits pois, des carottes et des oeufs",
    prix: 6.99,
    top: true,
    categorie: "Marocain",
    ingredients: ["riz", "petits pois", "carottes", "oeufs"],
  }
]
